### ISSUE TITLE
Tracking issue for libz blitz evaluation

### ISSUE THREAD

**Issue by KodrAus** [steveklabnik/semver-parser#24]
[The original discussion and guidelines checklist](https://internals.rust-lang.org/t/out-of-band-crate-evaluation-for-2017-10-13-semver/5929)

Also see: [the `semver` tracking issue](https://github.com/steveklabnik/semver/issues/139)

We've extracted the following contribution opportunities out of the libz blitz evaluation of `semver_parser`:

- [x] [Implement common traits for `VersionReq`](https://github.com/steveklabnik/semver-parser/issues/15)
- [x] [Implement common traits for `Version`](https://github.com/steveklabnik/semver-parser/issues/16)
- [x] [Add examples to public items and methods](https://github.com/steveklabnik/semver-parser/issues/17)
- [x] [Add readme, keywords and categories to Cargo.toml](https://github.com/steveklabnik/semver-parser/issues/18)
- [x] [Add html_root_url attribute to crate root](https://github.com/steveklabnik/semver-parser/issues/19)
- [x] [Make structures with public fields non-exhaustive](https://github.com/steveklabnik/semver-parser/issues/20)
- [ ] [Rename `Predicate` to `Comparator` and `VersionReq` to `Range`](https://github.com/steveklabnik/semver-parser/issues/21)
- [x] [Support parsing range sets](https://github.com/steveklabnik/semver-parser/issues/22)
- [x] [Add documentation to the crate root and public items](https://github.com/steveklabnik/semver-parser/issues/23)

# We need your help!

- If you'd like to do one of these just leave a comment on the issue saying you're working on it.
- If it's been a little while since an issue was claimed and there isn't a PR yet then feel free to re-claim it.
- If you wanted to work on something but just didn't get around to it then don't feel bad! That's ok, and if you'd like to try something else we've got plenty more contribution opportunities. Just reach out on [gitter](https://gitter.im/rust-impl-period/WG-libz-blitz)

Some of these issues need more discussion so we can work out bigger design questions and put together mentoring instructions. It'd be great if you could leave your thoughts on those issues!

**Comment by steveklabnik** [comment]
This crate is no longer being used or maintained: https://github.com/steveklabnik/semver-parser/commit/dc6c1077899da46e89242041dda54ca36c170982
